language: python
before_install:
- sudo add-apt-repository --yes ppa:fontforge/fontforge
- sudo apt-get update -qq
- sudo apt-get install python-fontforge
- cp /usr/lib/python2.7/dist-packages/fontforge.* "$HOME/virtualenv/python2.7.8/lib/python2.7/site-packages"
install:
- pip install git+https://github.com/behdad/fontTools.git
- pip install git+https://github.com/googlefonts/fontbakery-cli.git
- pip install jinja2
script: PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH fontbakery.py .
branches:
  only:
  - master
after_script:
- rm -rf builds/build/sources builds/build/build.state.yaml
- PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH bakery-report.py builds/build
- PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH travis-deploy.py
env:
  global:
    secure: 0b4HY+DZOy/hl5AucL+gzW/ZjT3T+m7Ku3dZLqmg7F8ZsLgxvqk+5DwUrlEed8huQlkeU4WdSTPOFOh1yFTgn7Aa55eTNxx4lVKF7+9Fn2eVX4u1QzrW1ripImg/V/dSpztu45Bt7DKCgrDrdsfCB4L5/WRSga6Wl1g2IPCFft0=
